name = "replicator-studio"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "replicator-studio-db"
database_id = "${CLOUDFLARE_D1_ID}"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "replicatorstudio"

[[kv_namespaces]]
binding = "CACHE"
id = "${CLOUDFLARE_KV_NAMESPACE_ID}"

[triggers]
crons = ["*/5 * * * *"] # Run every 5 minutes

[miniflare]
kv_persist = true
cache_persist = true

[[queues.producers]]
binding = "AUDIO_QUEUE"
queue = "audio-processing"

[[queues.consumers]]
queue = "audio-processing"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "failed-audio-processing"

# Monitoring
[monitoring]
dataset = "${AXIOM_DATASET}"
token = "${AXIOM_TOKEN}"